version: 0.0

os: linux 
files:
  - source: /
    destination: /home/ec2-user

hooks:

# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 1200
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
#   AfterInstall:
#     - location: scripts/after_install.sh
#       timeout: 300
#       runas: ec2-user
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: ubuntu
